import {
  Flex,
  Heading,
  Stack,
  Text,
} from "@chakra-ui/react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCreativeCommons,
  faCreativeCommonsBy,
} from "@fortawesome/free-brands-svg-icons";
import Head from "next/head";
import Image from "next/image";
import { Attribution, OtterButton } from "../components";

import styles from "../styles/Home.module.css";

export default function Home(props) {
  const { id, keyword, width, height, user, user_id, filename } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h1" size="3xl" fontFamily="primary" color="green.600">
          Am I Otter Not?!?
        </Heading>

        <Text color="yellow.800" fontFamily="secondary">
          {"mustelids don't give a shit"}
        </Text>

        <Stack>
          <Image
            src={`/pics/${filename}`}
            width={width}
            height={height}
            alt={`${keyword} pic`}
          />
          <Attribution user={user} user_id={user_id} />

          <Flex justify="space-around">
            <OtterButton id={id} isOtter={true}>
              Otter!
            </OtterButton>
            <OtterButton id={id} isOtter={false}>
              Not!
            </OtterButton>
          </Flex>
        </Stack>
      </main>

      <footer className={styles.footer}>
        <Text fontSize={"xs"}>
          <a href="https://amiotternot.com">amiotternot</a> by{" "}
          <a href="https://jaywritesco.de">jay harris</a> is{" "}
          <a
            href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1"
            target="_blank"
            rel="license noopener noreferrer"
          >
            licensed
          </a>{" "}
          under CC BY 4.0 <FontAwesomeIcon icon={faCreativeCommons} />{" "}
          <FontAwesomeIcon icon={faCreativeCommonsBy} />
        </Text>
      </footer>
    </div>
  );
}

import sqlite3 from "sqlite3";

const DATABASE = "pics.db";

export async function getServerSideProps(context) {
  const db = new sqlite3.Database(DATABASE);

  try {
    const result = await new Promise((resolve, reject) => {
      db.get(
        "SELECT id, keyword, width, height, user, user_id, filename FROM images ORDER BY random() limit 1",
        (err, row) => {
          if (err) reject(err);
          else resolve(row);
        }
      );
    });
    return { props: result };
  } catch (err) {
    return { notFound: true };
  }
}
